// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1:string):Promise<void>;

export function Delete(arg1:string):Promise<void>;

export function FrontEndReady():Promise<void>;

export function Pause(arg1:string,arg2:boolean):Promise<void>;

export function Save(arg1:string):Promise<void>;
