// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['DownloaderBackend']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['DownloaderBackend']['Delete'](arg1);
}

export function FrontEndReady() {
  return window['go']['main']['DownloaderBackend']['FrontEndReady']();
}

export function Pause(arg1, arg2) {
  return window['go']['main']['DownloaderBackend']['Pause'](arg1, arg2);
}

export function Save(arg1) {
  return window['go']['main']['DownloaderBackend']['Save'](arg1);
}
